In [1]:
# Script to generate max diversion rate and monthly total amounts for water rights reporting requirements

In [29]:
import pandas as pd
import numpy as np
import os.path
from pathlib import Path
from datetime import datetime

In [87]:
indata = os.path.join( os.getcwd(), '..', 'DataValues_Reviewed.csv' )
indata_filled = os.path.join( os.getcwd(), '..', 'DataValues_Reviewed_Filled_HourlyMean.csv' )
outdata_report = os.path.join( os.getcwd(), '..', 'SB88_WaterRightsReport.csv' )

In [53]:
#Import raw datda
df = pd.read_csv(indata)
df.head()

,LocalDateTime,UTCOffset,DateTimeUTC,VariableCode,SourceCode,QualityControlLevelCode,CensorCode,SiteCode,DataValue,MethodCode,QualifierCode
0,2018-01-01 00:00:00,-8.0,2018-01-01 08:00:00,GPM_5min,TNC,0,nc,Siphon11,NaN,IS203_EM,0
1,2018-01-01 00:05:00,-8.0,2018-01-01 08:05:00,GPM_5min,TNC,0,nc,Siphon11,NaN,IS203_EM,0
2,2018-01-01 00:10:00,-8.0,2018-01-01 08:10:00,GPM_5min,TNC,0,nc,Siphon11,NaN,IS203_EM,0
3,2018-01-01 00:15:00,-8.0,2018-01-01 08:15:00,GPM_5min,TNC,0,nc,Siphon11,NaN,IS203_EM,0
4,2018-01-01 00:20:00,-8.0,2018-01-01 08:20:00,GPM_5min,TNC,0,nc,Siphon11,NaN,IS203_EM,0

In [54]:
# Convert index to date index
df['LocalDateTime'] = pd.to_datetime(df['LocalDateTime'])
df.index = df['LocalDateTime']
#del df['LocalDateTime']
df

,LocalDateTime,UTCOffset,DateTimeUTC,VariableCode,SourceCode,QualityControlLevelCode,CensorCode,SiteCode,DataValue,MethodCode,QualifierCode
LocalDateTime,,,,,,,,,,,
2018-01-01 00:00:00,2018-01-01 00:00:00,-8.0,2018-01-01 08:00:00,GPM_5min,TNC,0,nc,Siphon11,NaN,IS203_EM,0
2018-01-01 00:05:00,2018-01-01 00:05:00,-8.0,2018-01-01 08:05:00,GPM_5min,TNC,0,nc,Siphon11,NaN,IS203_EM,0
2018-01-01 00:10:00,2018-01-01 00:10:00,-8.0,2018-01-01 08:10:00,GPM_5min,TNC,0,nc,Siphon11,NaN,IS203_EM,0
2018-01-01 00:15:00,2018-01-01 00:15:00,-8.0,2018-01-01 08:15:00,GPM_5min,TNC,0,nc,Siphon11,NaN,IS203_EM,0
2018-01-01 00:20:00,2018-01-01 00:20:00,-8.0,2018-01-01 08:20:00,GPM_5min,TNC,0,nc,Siphon11,NaN,IS203_EM,0
2018-01-01 00:25:00,2018-01-01 00:25:00,-8.0,2018-01-01 08:25:00,GPM_5min,TNC,0,nc,Siphon11,NaN,IS203_EM,0
2018-01-01 00:30:00,2018-01-01 00:30:00,-8.0,2018-01-01 08:30:00,GPM_5min,TNC,0,nc,Siphon11,NaN,IS203_EM,0
2018-01-01 00:35:00,2018-01-01 00:35:00,-8.0,2018-01-01 08:35:00,GPM_5min,TNC,0,nc,Siphon11,NaN,IS203_EM,0
2018-01-01 00:40:00,2018-01-01 00:40:00,-8.0,2018-01-01 08:40:00,GPM_5min,TNC,0,nc,Siphon11,NaN,IS203_EM,0
2018-01-01 00:45:00,2018-01-01 00:45:00,-8.0,2018-01-01 08:45:00,GPM_5min,TNC,0,nc,Siphon11,NaN,IS203_EM,0
2018-01-01 00:50:00,2018-01-01 00:50:00,-8.0,2018-01-01 08:50:00,GPM_5min,TNC,0,nc,Siphon11,NaN,IS203_EM,0
2018-01-01 00:55:00,2018-01-01 00:55:00,-8.0,2018-01-01 08:55:00,GPM_5min,TNC,0,nc,Siphon11,NaN,IS203_EM,0
2018-01-01 01:00:00,2018-01-01 01:00:00,-8.0,2018-01-01 09:00:00,GPM_5min,TNC,0,nc,Siphon11,NaN,IS203_EM,0
2018-01-01 01:05:00,2018-01-01 01:05:00,-8.0,2018-01-01 09:05:00,GPM_5min,TNC,0,nc,Siphon11,NaN,IS203_EM,0
2018-01-01 01:10:00,2018-01-01 01:10:00,-8.0,2018-01-01 09:10:00,GPM_5min,TNC,0,nc,Siphon11,NaN,IS203_EM,0
2018-01-01 01:15:00,2018-01-01 01:15:00,-8.0,2018-01-01 09:15:00,GPM_5min,TNC,0,nc,Siphon11,NaN,IS203_EM,0
2018-01-01 01:20:00,2018-01-01 01:20:00,-8.0,2018-01-01 09:20:00,GPM_5min,TNC,0,nc,Siphon11,NaN,IS203_EM,0
2018-01-01 01:25:00,2018-01-01 01:25:00,-8.0,2018-01-01 09:25:00,GPM_5min,TNC,0,nc,Siphon11,NaN,IS203_EM,0
2018-01-01 01:30:00,2018-01-01 01:30:00,-8.0,2018-01-01 09:30:00,GPM_5min,TNC,0,nc,Siphon11,NaN,IS203_EM,0
2018-01-01 01:35:00,2018-01-01 01:35:00,-8.0,2018-01-01 09:35:00,GPM_5min,TNC,0,nc,Siphon11,NaN,IS203_EM,0
2018-01-01 01:40:00,2018-01-01 01:40:00,-8.0,2018-01-01 09:40:00,GPM_5min,TNC,0,nc,Siphon11,NaN,IS203_EM,0
2018-01-01 01:45:00,2018-01-01 01:45:00,-8.0,2018-01-01 09:45:00,GPM_5min,TNC,0,nc,Siphon11,NaN,IS203_EM,0
2018-01-01 01:50:00,2018-01-01 01:50:00,-8.0,2018-01-01 09:50:00,GPM_5min,TNC,0,nc,Siphon11,NaN,IS203_EM,0
2018-01-01 01:55:00,2018-01-01 01:55:00,-8.0,2018-01-01 09:55:00,GPM_5min,TNC,0,nc,Siphon11,NaN,IS203_EM,0
2018-01-01 02:00:00,2018-01-01 02:00:00,-8.0,2018-01-01 10:00:00,GPM_5min,TNC,0,nc,Siphon11,NaN,IS203_EM,0
2018-01-01 02:05:00,2018-01-01 02:05:00,-8.0,2018-01-01 10:05:00,GPM_5min,TNC,0,nc,Siphon11,NaN,IS203_EM,0
2018-01-01 02:10:00,2018-01-01 02:10:00,-8.0,2018-01-01 10:10:00,GPM_5min,TNC,0,nc,Siphon11,NaN,IS203_EM,0
2018-01-01 02:15:00,2018-01-01 02:15:00,-8.0,2018-01-01 10:15:00,GPM_5min,TNC,0,nc,Siphon11,NaN,IS203_EM,0
2018-01-01 02:20:00,2018-01-01 02:20:00,-8.0,2018-01-01 10:20:00,GPM_5min,TNC,0,nc,Siphon11,NaN,IS203_EM,0
2018-01-01 02:25:00,2018-01-01 02:25:00,-8.0,2018-01-01 10:25:00,GPM_5min,TNC,0,nc,Siphon11,NaN,IS203_EM,0
...,...,...,...,...,...,...,...,...,...,...,...
2018-12-31 22:50:00,2018-12-31 22:50:00,-8.0,2019-01-01 06:50:00,GPM_5min,TNC,0,nc,Siphon7,0.0,IS203_EM,0
2018-12-31 22:50:00,2018-12-31 22:50:00,-8.0,2019-01-01 06:50:00,GPM_5min,TNC,0,nc,Siphon7,0.0,AG3000_EM,0
2018-12-31 22:55:00,2018-12-31 22:55:00,-8.0,2019-01-01 06:55:00,GPM_5min,TNC,0,nc,Siphon7,0.0,IS203_EM,0
2018-12-31 22:55:00,2018-12-31 22:55:00,-8.0,2019-01-01 06:55:00,GPM_5min,TNC,0,nc,Siphon7,0.0,AG3000_EM,0
2018-12-31 23:00:00,2018-12-31 23:00:00,-8.0,2019-01-01 07:00:00,GPM_5min,TNC,0,nc,Siphon7,0.0,IS203_EM,0
2018-12-31 23:00:00,2018-12-31 23:00:00,-8.0,2019-01-01 07:00:00,GPM_5min,TNC,0,nc,Siphon7,0.0,AG3000_EM,0
2018-12-31 23:05:00,2018-12-31 23:05:00,-8.0,2019-01-01 07:05:00,GPM_5min,TNC,0,nc,Siphon7,0.0,IS203_EM,0
2018-12-31 23:05:00,2018-12-31 23:05:00,-8.0,2019-01-01 07:05:00,GPM_5min,TNC,0,nc,Siphon7,0.0,AG3000_EM,0
2018-12-31 23:10:00,2018-12-31 23:10:00,-8.0,2019-01-01 07:10:00,GPM_5min,TNC,0,nc,Siphon7,0.0,IS203_EM,0
2018-12-31 23:10:00,2018-12-31 23:10:00,-8.0,2019-01-01 07:10:00,GPM_5min,TNC,0,nc,Siphon7,0.0,AG3000_EM,0
2018-12-31 23:15:00,2018-12-31 23:15:00,-8.0,2019-01-01 07:15:00,GPM_5min,TNC,0,nc,Siphon7,0.0,IS203_EM,0
2018-12-31 23:15:00,2018-12-31 23:15:00,-8.0,2019-01-01 07:15:00,GPM_5min,TNC,0,nc,Siphon7,0.0,AG3000_EM,0
2018-12-31 23:20:00,2018-12-31 23:20:00,-8.0,2019-01-01 07:20:00,GPM_5min,TNC,0,nc,Siphon7,0.0,IS203_EM,0
2018-12-31 23:20:00,2018-12-31 23:20:00,-8.0,2019-01-01 07:20:00,GPM_5min,TNC,0,nc,Siphon7,0.0,AG3000_EM,0
2018-12-31 23:25:00,2018-12-31 23:25:00,-8.0,2019-01-01 07:25:00,GPM_5min,TNC,0,nc,Siphon7,0.0,IS203_EM,0
2018-12-31 23:25:00,2018-12-31 23:25:00,-8.0,2019-01-01 07:25:00,GPM_5min,TNC,0,nc,Siphon7,0.0,AG3000_EM,0
2018-12-31 23:30:00,2018-12-31 23:30:00,-8.0,2019-01-01 07:30:00,GPM_5min,TNC,0,nc,Siphon7,0.0,IS203_EM,0
2018-12-31 23:30:00,2018-12-31 23:30:00,-8.0,2019-01-01 07:30:00,GPM_5min,TNC,0,nc,Siphon7,0.0,AG3000_EM,0
2018-12-31 23:35:00,2018-12-31 23:35:00,-8.0,2019-01-01 07:35:00,GPM_5min,TNC,0,nc,Siphon7,0.0,IS203_EM,0
2018-12-31 23:35:00,2018-12-31 23:35:00,-8.0,2019-01-01 07:35:00,GPM_5min,TNC,0,nc,Siphon7,0.0,AG3000_EM,0
2018-12-31 23:40:00,2018-12-31 23:40:00,-8.0,2019-01-01 07:40:00,GPM_5min,TNC,0,nc,Siphon7,0.0,IS203_EM,0
2018-12-31 23:40:00,2018-12-31 23:40:00,-8.0,2019-01-01 07:40:00,GPM_5min,TNC,0,nc,Siphon7,0.0,AG3000_EM,0
2018-12-31 23:45:00,2018-12-31 23:45:00,-8.0,2019-01-01 07:45:00,GPM_5min,TNC,0,nc,Siphon7,0.0,IS203_EM,0
2018-12-31 23:45:00,2018-12-31 23:45:00,-8.0,2019-01-01 07:45:00,GPM_5min,TNC,0,nc,Siphon7,0.0,AG3000_EM,0
2018-12-31 23:50:00,2018-12-31 23:50:00,-8.0,2019-01-01 07:50:00,GPM_5min,TNC,0,nc,Siphon7,0.0,IS203_EM,0
2018-12-31 23:50:00,2018-12-31 23:50:00,-8.0,2019-01-01 07:50:00,GPM_5min,TNC,0,nc,Siphon7,0.0,AG3000_EM,0
2018-12-31 23:55:00,2018-12-31 23:55:00,-8.0,2019-01-01 07:55:00,GPM_5min,TNC,0,nc,Siphon7,0.0,IS203_EM,0
2018-12-31 23:55:00,2018-12-31 23:55:00,-8.0,2019-01-01 07:55:00,GPM_5min,TNC,0,nc,Siphon7,0.0,AG3000_EM,0
2019-01-01 00:00:00,2019-01-01 00:00:00,-8.0,2019-01-01 08:00:00,GPM_5min,TNC,0,nc,Siphon7,0.0,IS203_EM,0
2019-01-01 00:00:00,2019-01-01 00:00:00,-8.0,2019-01-01 08:00:00,GPM_5min,TNC,0,nc,Siphon7,0.0,AG3000_EM,0

# Create Maximum Rate of Diversion from raw 5 min data (without outliers)

In [55]:
# Set outlier values to missing

df.loc[df['QualifierCode'] == 1, 'DataValue'] = np.nan

In [56]:

# Clip any 2019 data
mask = (df['LocalDateTime'] >= '2018-1-1') & (df['LocalDateTime'] < '2019-1-1')
df = df.loc[mask]

In [57]:
# Generate the maximum rate for the DataValue column for each month
df_max = df.groupby(['SiteCode','MethodCode']).resample('M').max()
df_max = df_max["DataValue"].reset_index()
df_max

    SiteCode MethodCode LocalDateTime  DataValue
0   Siphon11   IS203_EM    2018-01-31        NaN
1   Siphon11   IS203_EM    2018-02-28        NaN
2   Siphon11   IS203_EM    2018-03-31        NaN
3   Siphon11   IS203_EM    2018-04-30        NaN
4   Siphon11   IS203_EM    2018-05-31     2520.0
5   Siphon11   IS203_EM    2018-06-30     4140.0
6   Siphon11   IS203_EM    2018-07-31     5060.0
7   Siphon11   IS203_EM    2018-08-31        0.0
8   Siphon11   IS203_EM    2018-09-30        0.0
9   Siphon11   IS203_EM    2018-10-31        0.0
10  Siphon11   IS203_EM    2018-11-30      280.0
11  Siphon11   IS203_EM    2018-12-31      200.0
12  Siphon15   IS203_EM    2018-01-31        NaN
13  Siphon15   IS203_EM    2018-02-28        NaN
14  Siphon15   IS203_EM    2018-03-31        NaN
15  Siphon15   IS203_EM    2018-04-30        NaN
16  Siphon15   IS203_EM    2018-05-31       20.0
17  Siphon15   IS203_EM    2018-06-30     4080.0
18  Siphon15   IS203_EM    2018-07-31     4140.0
19  Siphon15   IS203_EM    2018-08-31     4740.0
20  Siphon15   IS203_EM    2018-09-30       60.0
21  Siphon15   IS203_EM    2018-10-31        0.0
22  Siphon15   IS203_EM    2018-11-30     5380.0
23  Siphon15   IS203_EM    2018-12-31       80.0
24  Siphon30   IS203_EM    2018-01-31        NaN
25  Siphon30   IS203_EM    2018-02-28        NaN
26  Siphon30   IS203_EM    2018-03-31        NaN
27  Siphon30   IS203_EM    2018-04-30       40.0
28  Siphon30   IS203_EM    2018-05-31     4740.0
29  Siphon30   IS203_EM    2018-06-30     5260.0
..       ...        ...           ...        ...
54  Siphon40   IS203_EM    2018-07-31     4820.0
55  Siphon40   IS203_EM    2018-08-31     4400.0
56  Siphon40   IS203_EM    2018-09-30     4200.0
57  Siphon40   IS203_EM    2018-10-31        0.0
58  Siphon40   IS203_EM    2018-11-30        0.0
59  Siphon40   IS203_EM    2018-12-31        0.0
60   Siphon7  AG3000_EM    2018-01-31     3420.0
61   Siphon7  AG3000_EM    2018-02-28        0.0
62   Siphon7  AG3000_EM    2018-03-31        0.0
63   Siphon7  AG3000_EM    2018-04-30        0.0
64   Siphon7  AG3000_EM    2018-05-31        0.0
65   Siphon7  AG3000_EM    2018-06-30     3060.0
66   Siphon7  AG3000_EM    2018-07-31     2520.0
67   Siphon7  AG3000_EM    2018-08-31     2100.0
68   Siphon7  AG3000_EM    2018-09-30        0.0
69   Siphon7  AG3000_EM    2018-10-31        0.0
70   Siphon7  AG3000_EM    2018-11-30        0.0
71   Siphon7  AG3000_EM    2018-12-31        0.0
72   Siphon7   IS203_EM    2018-01-31     3160.0
73   Siphon7   IS203_EM    2018-02-28       40.0
74   Siphon7   IS203_EM    2018-03-31        0.0
75   Siphon7   IS203_EM    2018-04-30        0.0
76   Siphon7   IS203_EM    2018-05-31        0.0
77   Siphon7   IS203_EM    2018-06-30     3140.0
78   Siphon7   IS203_EM    2018-07-31     2540.0
79   Siphon7   IS203_EM    2018-08-31     2100.0
80   Siphon7   IS203_EM    2018-09-30        0.0
81   Siphon7   IS203_EM    2018-10-31        0.0
82   Siphon7   IS203_EM    2018-11-30        0.0
83   Siphon7   IS203_EM    2018-12-31        0.0

[84 rows x 4 columns]

In [58]:
# Convert the LocalDateTime to year and month
df_max["Month"] = df_max["LocalDateTime"].dt.month_name()
df_max["Year"] = df_max["LocalDateTime"].dt.year
df_max

    SiteCode MethodCode LocalDateTime  DataValue      Month  Year
0   Siphon11   IS203_EM    2018-01-31        NaN    January  2018
1   Siphon11   IS203_EM    2018-02-28        NaN   February  2018
2   Siphon11   IS203_EM    2018-03-31        NaN      March  2018
3   Siphon11   IS203_EM    2018-04-30        NaN      April  2018
4   Siphon11   IS203_EM    2018-05-31     2520.0        May  2018
5   Siphon11   IS203_EM    2018-06-30     4140.0       June  2018
6   Siphon11   IS203_EM    2018-07-31     5060.0       July  2018
7   Siphon11   IS203_EM    2018-08-31        0.0     August  2018
8   Siphon11   IS203_EM    2018-09-30        0.0  September  2018
9   Siphon11   IS203_EM    2018-10-31        0.0    October  2018
10  Siphon11   IS203_EM    2018-11-30      280.0   November  2018
11  Siphon11   IS203_EM    2018-12-31      200.0   December  2018
12  Siphon15   IS203_EM    2018-01-31        NaN    January  2018
13  Siphon15   IS203_EM    2018-02-28        NaN   February  2018
14  Siphon15   IS203_EM    2018-03-31        NaN      March  2018
15  Siphon15   IS203_EM    2018-04-30        NaN      April  2018
16  Siphon15   IS203_EM    2018-05-31       20.0        May  2018
17  Siphon15   IS203_EM    2018-06-30     4080.0       June  2018
18  Siphon15   IS203_EM    2018-07-31     4140.0       July  2018
19  Siphon15   IS203_EM    2018-08-31     4740.0     August  2018
20  Siphon15   IS203_EM    2018-09-30       60.0  September  2018
21  Siphon15   IS203_EM    2018-10-31        0.0    October  2018
22  Siphon15   IS203_EM    2018-11-30     5380.0   November  2018
23  Siphon15   IS203_EM    2018-12-31       80.0   December  2018
24  Siphon30   IS203_EM    2018-01-31        NaN    January  2018
25  Siphon30   IS203_EM    2018-02-28        NaN   February  2018
26  Siphon30   IS203_EM    2018-03-31        NaN      March  2018
27  Siphon30   IS203_EM    2018-04-30       40.0      April  2018
28  Siphon30   IS203_EM    2018-05-31     4740.0        May  2018
29  Siphon30   IS203_EM    2018-06-30     5260.0       June  2018
..       ...        ...           ...        ...        ...   ...
54  Siphon40   IS203_EM    2018-07-31     4820.0       July  2018
55  Siphon40   IS203_EM    2018-08-31     4400.0     August  2018
56  Siphon40   IS203_EM    2018-09-30     4200.0  September  2018
57  Siphon40   IS203_EM    2018-10-31        0.0    October  2018
58  Siphon40   IS203_EM    2018-11-30        0.0   November  2018
59  Siphon40   IS203_EM    2018-12-31        0.0   December  2018
60   Siphon7  AG3000_EM    2018-01-31     3420.0    January  2018
61   Siphon7  AG3000_EM    2018-02-28        0.0   February  2018
62   Siphon7  AG3000_EM    2018-03-31        0.0      March  2018
63   Siphon7  AG3000_EM    2018-04-30        0.0      April  2018
64   Siphon7  AG3000_EM    2018-05-31        0.0        May  2018
65   Siphon7  AG3000_EM    2018-06-30     3060.0       June  2018
66   Siphon7  AG3000_EM    2018-07-31     2520.0       July  2018
67   Siphon7  AG3000_EM    2018-08-31     2100.0     August  2018
68   Siphon7  AG3000_EM    2018-09-30        0.0  September  2018
69   Siphon7  AG3000_EM    2018-10-31        0.0    October  2018
70   Siphon7  AG3000_EM    2018-11-30        0.0   November  2018
71   Siphon7  AG3000_EM    2018-12-31        0.0   December  2018
72   Siphon7   IS203_EM    2018-01-31     3160.0    January  2018
73   Siphon7   IS203_EM    2018-02-28       40.0   February  2018
74   Siphon7   IS203_EM    2018-03-31        0.0      March  2018
75   Siphon7   IS203_EM    2018-04-30        0.0      April  2018
76   Siphon7   IS203_EM    2018-05-31        0.0        May  2018
77   Siphon7   IS203_EM    2018-06-30     3140.0       June  2018
78   Siphon7   IS203_EM    2018-07-31     2540.0       July  2018
79   Siphon7   IS203_EM    2018-08-31     2100.0     August  2018
80   Siphon7   IS203_EM    2018-09-30        0.0  September  2018
81   Siphon7   IS203_EM    2018-10-31        0.0    October  2018
82   Siphon7   IS203_EM    2018-11-30        0.0   November  2018
83   Siphon7   IS203_EM    2018-12-31        0.0   December  2018

[84 rows x 6 columns]

In [59]:
#Clean up columns
df_max.rename(columns={'DataValue': 'Maximum Rate of Diversion (GPM)', 'SiteCode':'Siphon','MethodCode':'Meter'}, inplace=True)
df_max.drop(['LocalDateTime'], axis=1, inplace=True)
df_max.head()

     Siphon     Meter  Maximum Rate of Diversion (GPM)     Month  Year
0  Siphon11  IS203_EM                              NaN   January  2018
1  Siphon11  IS203_EM                              NaN  February  2018
2  Siphon11  IS203_EM                              NaN     March  2018
3  Siphon11  IS203_EM                              NaN     April  2018
4  Siphon11  IS203_EM                           2520.0       May  2018

# Generate Monthly totals from hourly filled data

In [60]:
# Read in the reviewed data with gaps filled
df = pd.read_csv(indata_filled)
df.head()

,DateTimeUTC,SiteCode,MethodCode,UTCOffset,QualityControlLevelCode,DataValue,QualifierCode,LocalDateTime,SourceCode,CensorCode,VariableCode
0,2018-01-01 08:00:00,Siphon11,IS203_EM,-8.0,1,0.0,3,2018-01-01 00:00:00,TNC,nc,GPM_60min
1,2018-01-01 09:00:00,Siphon11,IS203_EM,-8.0,1,0.0,3,2018-01-01 01:00:00,TNC,nc,GPM_60min
2,2018-01-01 10:00:00,Siphon11,IS203_EM,-8.0,1,0.0,3,2018-01-01 02:00:00,TNC,nc,GPM_60min
3,2018-01-01 11:00:00,Siphon11,IS203_EM,-8.0,1,0.0,3,2018-01-01 03:00:00,TNC,nc,GPM_60min
4,2018-01-01 12:00:00,Siphon11,IS203_EM,-8.0,1,0.0,3,2018-01-01 04:00:00,TNC,nc,GPM_60min

In [61]:
# Convert index to date index
df['LocalDateTime'] = pd.to_datetime(df['LocalDateTime'])
df.index = df['LocalDateTime']
del df['LocalDateTime']
df.head()

,DateTimeUTC,SiteCode,MethodCode,UTCOffset,QualityControlLevelCode,DataValue,QualifierCode,SourceCode,CensorCode,VariableCode
LocalDateTime,,,,,,,,,,
2018-01-01 00:00:00,2018-01-01 08:00:00,Siphon11,IS203_EM,-8.0,1,0.0,3,TNC,nc,GPM_60min
2018-01-01 01:00:00,2018-01-01 09:00:00,Siphon11,IS203_EM,-8.0,1,0.0,3,TNC,nc,GPM_60min
2018-01-01 02:00:00,2018-01-01 10:00:00,Siphon11,IS203_EM,-8.0,1,0.0,3,TNC,nc,GPM_60min
2018-01-01 03:00:00,2018-01-01 11:00:00,Siphon11,IS203_EM,-8.0,1,0.0,3,TNC,nc,GPM_60min
2018-01-01 04:00:00,2018-01-01 12:00:00,Siphon11,IS203_EM,-8.0,1,0.0,3,TNC,nc,GPM_60min

In [62]:
# Create monthly totals of amount diverted
df["Diverted (Gallons)"] = df['DataValue'] * 60 #Convert gallons per minue to gallons per hour
df_sum = df.groupby(['SiteCode','MethodCode']).resample('M').sum()
df_sum = df_sum["Diverted (Gallons)"].reset_index()
df_sum['Diverted (Acre Feet)'] = df_sum["Diverted (Gallons)"] / 325851
df_sum

,SiteCode,MethodCode,LocalDateTime,Diverted (Gallons),Diverted (Acre Feet)
0,Siphon11,IS203_EM,2018-01-31,0.000000e+00,0.000000
1,Siphon11,IS203_EM,2018-02-28,0.000000e+00,0.000000
2,Siphon11,IS203_EM,2018-03-31,0.000000e+00,0.000000
3,Siphon11,IS203_EM,2018-04-30,0.000000e+00,0.000000
4,Siphon11,IS203_EM,2018-05-31,1.991882e+06,6.112861
5,Siphon11,IS203_EM,2018-06-30,4.981926e+07,152.889690
6,Siphon11,IS203_EM,2018-07-31,1.144068e+08,351.101473
7,Siphon11,IS203_EM,2018-08-31,0.000000e+00,0.000000
8,Siphon11,IS203_EM,2018-09-30,0.000000e+00,0.000000
9,Siphon11,IS203_EM,2018-10-31,0.000000e+00,0.000000
10,Siphon11,IS203_EM,2018-11-30,3.696810e+05,1.134509
11,Siphon11,IS203_EM,2018-12-31,3.300000e+03,0.010127
12,Siphon15,IS203_EM,2018-01-31,0.000000e+00,0.000000
13,Siphon15,IS203_EM,2018-02-28,0.000000e+00,0.000000
14,Siphon15,IS203_EM,2018-03-31,0.000000e+00,0.000000
15,Siphon15,IS203_EM,2018-04-30,0.000000e+00,0.000000
16,Siphon15,IS203_EM,2018-05-31,1.000000e+02,0.000307
17,Siphon15,IS203_EM,2018-06-30,1.965299e+07,60.312799
18,Siphon15,IS203_EM,2018-07-31,4.228019e+07,129.753136
19,Siphon15,IS203_EM,2018-08-31,7.683729e+07,235.804974
20,Siphon15,IS203_EM,2018-09-30,1.300649e+03,0.003992
21,Siphon15,IS203_EM,2018-10-31,0.000000e+00,0.000000
22,Siphon15,IS203_EM,2018-11-30,4.962967e+07,152.307869
23,Siphon15,IS203_EM,2018-12-31,1.947922e+04,0.059780
24,Siphon30,IS203_EM,2018-01-31,0.000000e+00,0.000000
25,Siphon30,IS203_EM,2018-02-28,0.000000e+00,0.000000
26,Siphon30,IS203_EM,2018-03-31,0.000000e+00,0.000000
27,Siphon30,IS203_EM,2018-04-30,4.000000e+02,0.001228
28,Siphon30,IS203_EM,2018-05-31,2.030286e+07,62.307201
29,Siphon30,IS203_EM,2018-06-30,8.169758e+07,250.720671
...,...,...,...,...,...
54,Siphon40,IS203_EM,2018-07-31,1.291664e+08,396.397178
55,Siphon40,IS203_EM,2018-08-31,1.325126e+08,406.666255
56,Siphon40,IS203_EM,2018-09-30,2.028260e+07,62.245025
57,Siphon40,IS203_EM,2018-10-31,0.000000e+00,0.000000
58,Siphon40,IS203_EM,2018-11-30,0.000000e+00,0.000000
59,Siphon40,IS203_EM,2018-12-31,0.000000e+00,0.000000
60,Siphon7,AG3000_EM,2018-01-31,5.163055e+06,15.844833
61,Siphon7,AG3000_EM,2018-02-28,0.000000e+00,0.000000
62,Siphon7,AG3000_EM,2018-03-31,0.000000e+00,0.000000
63,Siphon7,AG3000_EM,2018-04-30,0.000000e+00,0.000000
64,Siphon7,AG3000_EM,2018-05-31,0.000000e+00,0.000000
65,Siphon7,AG3000_EM,2018-06-30,1.831113e+07,56.194800
66,Siphon7,AG3000_EM,2018-07-31,4.185869e+07,128.459614
67,Siphon7,AG3000_EM,2018-08-31,2.894506e+07,88.829124
68,Siphon7,AG3000_EM,2018-09-30,0.000000e+00,0.000000
69,Siphon7,AG3000_EM,2018-10-31,0.000000e+00,0.000000
70,Siphon7,AG3000_EM,2018-11-30,0.000000e+00,0.000000
71,Siphon7,AG3000_EM,2018-12-31,0.000000e+00,0.000000
72,Siphon7,IS203_EM,2018-01-31,2.246245e+06,6.893474
73,Siphon7,IS203_EM,2018-02-28,2.181818e+02,0.000670
74,Siphon7,IS203_EM,2018-03-31,0.000000e+00,0.000000
75,Siphon7,IS203_EM,2018-04-30,0.000000e+00,0.000000
76,Siphon7,IS203_EM,2018-05-31,0.000000e+00,0.000000
77,Siphon7,IS203_EM,2018-06-30,1.831941e+07,56.220206
78,Siphon7,IS203_EM,2018-07-31,4.204429e+07,129.029183
79,Siphon7,IS203_EM,2018-08-31,2.903587e+07,89.107805
80,Siphon7,IS203_EM,2018-09-30,0.000000e+00,0.000000
81,Siphon7,IS203_EM,2018-10-31,0.000000e+00,0.000000
82,Siphon7,IS203_EM,2018-11-30,0.000000e+00,0.000000
83,Siphon7,IS203_EM,2018-12-31,0.000000e+00,0.000000

In [63]:
# Convert the LocalDateTime to year and month
df_sum["Month"] = df_sum["LocalDateTime"].dt.month_name()
df_sum["Year"] = df_sum["LocalDateTime"].dt.year
df_sum

,SiteCode,MethodCode,LocalDateTime,Diverted (Gallons),Diverted (Acre Feet),Month,Year
0,Siphon11,IS203_EM,2018-01-31,0.000000e+00,0.000000,January,2018
1,Siphon11,IS203_EM,2018-02-28,0.000000e+00,0.000000,February,2018
2,Siphon11,IS203_EM,2018-03-31,0.000000e+00,0.000000,March,2018
3,Siphon11,IS203_EM,2018-04-30,0.000000e+00,0.000000,April,2018
4,Siphon11,IS203_EM,2018-05-31,1.991882e+06,6.112861,May,2018
5,Siphon11,IS203_EM,2018-06-30,4.981926e+07,152.889690,June,2018
6,Siphon11,IS203_EM,2018-07-31,1.144068e+08,351.101473,July,2018
7,Siphon11,IS203_EM,2018-08-31,0.000000e+00,0.000000,August,2018
8,Siphon11,IS203_EM,2018-09-30,0.000000e+00,0.000000,September,2018
9,Siphon11,IS203_EM,2018-10-31,0.000000e+00,0.000000,October,2018
10,Siphon11,IS203_EM,2018-11-30,3.696810e+05,1.134509,November,2018
11,Siphon11,IS203_EM,2018-12-31,3.300000e+03,0.010127,December,2018
12,Siphon15,IS203_EM,2018-01-31,0.000000e+00,0.000000,January,2018
13,Siphon15,IS203_EM,2018-02-28,0.000000e+00,0.000000,February,2018
14,Siphon15,IS203_EM,2018-03-31,0.000000e+00,0.000000,March,2018
15,Siphon15,IS203_EM,2018-04-30,0.000000e+00,0.000000,April,2018
16,Siphon15,IS203_EM,2018-05-31,1.000000e+02,0.000307,May,2018
17,Siphon15,IS203_EM,2018-06-30,1.965299e+07,60.312799,June,2018
18,Siphon15,IS203_EM,2018-07-31,4.228019e+07,129.753136,July,2018
19,Siphon15,IS203_EM,2018-08-31,7.683729e+07,235.804974,August,2018
20,Siphon15,IS203_EM,2018-09-30,1.300649e+03,0.003992,September,2018
21,Siphon15,IS203_EM,2018-10-31,0.000000e+00,0.000000,October,2018
22,Siphon15,IS203_EM,2018-11-30,4.962967e+07,152.307869,November,2018
23,Siphon15,IS203_EM,2018-12-31,1.947922e+04,0.059780,December,2018
24,Siphon30,IS203_EM,2018-01-31,0.000000e+00,0.000000,January,2018
25,Siphon30,IS203_EM,2018-02-28,0.000000e+00,0.000000,February,2018
26,Siphon30,IS203_EM,2018-03-31,0.000000e+00,0.000000,March,2018
27,Siphon30,IS203_EM,2018-04-30,4.000000e+02,0.001228,April,2018
28,Siphon30,IS203_EM,2018-05-31,2.030286e+07,62.307201,May,2018
29,Siphon30,IS203_EM,2018-06-30,8.169758e+07,250.720671,June,2018
...,...,...,...,...,...,...,...
54,Siphon40,IS203_EM,2018-07-31,1.291664e+08,396.397178,July,2018
55,Siphon40,IS203_EM,2018-08-31,1.325126e+08,406.666255,August,2018
56,Siphon40,IS203_EM,2018-09-30,2.028260e+07,62.245025,September,2018
57,Siphon40,IS203_EM,2018-10-31,0.000000e+00,0.000000,October,2018
58,Siphon40,IS203_EM,2018-11-30,0.000000e+00,0.000000,November,2018
59,Siphon40,IS203_EM,2018-12-31,0.000000e+00,0.000000,December,2018
60,Siphon7,AG3000_EM,2018-01-31,5.163055e+06,15.844833,January,2018
61,Siphon7,AG3000_EM,2018-02-28,0.000000e+00,0.000000,February,2018
62,Siphon7,AG3000_EM,2018-03-31,0.000000e+00,0.000000,March,2018
63,Siphon7,AG3000_EM,2018-04-30,0.000000e+00,0.000000,April,2018
64,Siphon7,AG3000_EM,2018-05-31,0.000000e+00,0.000000,May,2018
65,Siphon7,AG3000_EM,2018-06-30,1.831113e+07,56.194800,June,2018
66,Siphon7,AG3000_EM,2018-07-31,4.185869e+07,128.459614,July,2018
67,Siphon7,AG3000_EM,2018-08-31,2.894506e+07,88.829124,August,2018
68,Siphon7,AG3000_EM,2018-09-30,0.000000e+00,0.000000,September,2018
69,Siphon7,AG3000_EM,2018-10-31,0.000000e+00,0.000000,October,2018
70,Siphon7,AG3000_EM,2018-11-30,0.000000e+00,0.000000,November,2018
71,Siphon7,AG3000_EM,2018-12-31,0.000000e+00,0.000000,December,2018
72,Siphon7,IS203_EM,2018-01-31,2.246245e+06,6.893474,January,2018
73,Siphon7,IS203_EM,2018-02-28,2.181818e+02,0.000670,February,2018
74,Siphon7,IS203_EM,2018-03-31,0.000000e+00,0.000000,March,2018
75,Siphon7,IS203_EM,2018-04-30,0.000000e+00,0.000000,April,2018
76,Siphon7,IS203_EM,2018-05-31,0.000000e+00,0.000000,May,2018
77,Siphon7,IS203_EM,2018-06-30,1.831941e+07,56.220206,June,2018
78,Siphon7,IS203_EM,2018-07-31,4.204429e+07,129.029183,July,2018
79,Siphon7,IS203_EM,2018-08-31,2.903587e+07,89.107805,August,2018
80,Siphon7,IS203_EM,2018-09-30,0.000000e+00,0.000000,September,2018
81,Siphon7,IS203_EM,2018-10-31,0.000000e+00,0.000000,October,2018
82,Siphon7,IS203_EM,2018-11-30,0.000000e+00,0.000000,November,2018
83,Siphon7,IS203_EM,2018-12-31,0.000000e+00,0.000000,December,2018

In [64]:
#Clean up columns
df_sum.rename(columns={'Diverted (Acre Feet)': 'Amount Directly Diverted (Acre Feet)', 'SiteCode':'Siphon','MethodCode':'Meter'}, inplace=True)
df_sum.drop(['LocalDateTime', 'Diverted (Gallons)'], axis=1, inplace=True)
df_sum.head()

     Siphon     Meter  Amount Directly Diverted (Acre Feet)     Month  Year
0  Siphon11  IS203_EM                              0.000000   January  2018
1  Siphon11  IS203_EM                              0.000000  February  2018
2  Siphon11  IS203_EM                              0.000000     March  2018
3  Siphon11  IS203_EM                              0.000000     April  2018
4  Siphon11  IS203_EM                              6.112861       May  2018

In [74]:
df_sum

      Siphon      Meter  Amount Directly Diverted (Acre Feet)      Month  Year
0   Siphon11   IS203_EM                              0.000000    January  2018
1   Siphon11   IS203_EM                              0.000000   February  2018
2   Siphon11   IS203_EM                              0.000000      March  2018
3   Siphon11   IS203_EM                              0.000000      April  2018
4   Siphon11   IS203_EM                              6.112861        May  2018
5   Siphon11   IS203_EM                            152.889690       June  2018
6   Siphon11   IS203_EM                            351.101473       July  2018
7   Siphon11   IS203_EM                              0.000000     August  2018
8   Siphon11   IS203_EM                              0.000000  September  2018
9   Siphon11   IS203_EM                              0.000000    October  2018
10  Siphon11   IS203_EM                              1.134509   November  2018
11  Siphon11   IS203_EM                              0.010127   December  2018
12  Siphon15   IS203_EM                              0.000000    January  2018
13  Siphon15   IS203_EM                              0.000000   February  2018
14  Siphon15   IS203_EM                              0.000000      March  2018
15  Siphon15   IS203_EM                              0.000000      April  2018
16  Siphon15   IS203_EM                              0.000307        May  2018
17  Siphon15   IS203_EM                             60.312799       June  2018
18  Siphon15   IS203_EM                            129.753136       July  2018
19  Siphon15   IS203_EM                            235.804974     August  2018
20  Siphon15   IS203_EM                              0.003992  September  2018
21  Siphon15   IS203_EM                              0.000000    October  2018
22  Siphon15   IS203_EM                            152.307869   November  2018
23  Siphon15   IS203_EM                              0.059780   December  2018
24  Siphon30   IS203_EM                              0.000000    January  2018
25  Siphon30   IS203_EM                              0.000000   February  2018
26  Siphon30   IS203_EM                              0.000000      March  2018
27  Siphon30   IS203_EM                              0.001228      April  2018
28  Siphon30   IS203_EM                             62.307201        May  2018
29  Siphon30   IS203_EM                            250.720671       June  2018
..       ...        ...                                   ...        ...   ...
54  Siphon40   IS203_EM                            396.397178       July  2018
55  Siphon40   IS203_EM                            406.666255     August  2018
56  Siphon40   IS203_EM                             62.245025  September  2018
57  Siphon40   IS203_EM                              0.000000    October  2018
58  Siphon40   IS203_EM                              0.000000   November  2018
59  Siphon40   IS203_EM                              0.000000   December  2018
60   Siphon7  AG3000_EM                             15.844833    January  2018
61   Siphon7  AG3000_EM                              0.000000   February  2018
62   Siphon7  AG3000_EM                              0.000000      March  2018
63   Siphon7  AG3000_EM                              0.000000      April  2018
64   Siphon7  AG3000_EM                              0.000000        May  2018
65   Siphon7  AG3000_EM                             56.194800       June  2018
66   Siphon7  AG3000_EM                            128.459614       July  2018
67   Siphon7  AG3000_EM                             88.829124     August  2018
68   Siphon7  AG3000_EM                              0.000000  September  2018
69   Siphon7  AG3000_EM                              0.000000    October  2018
70   Siphon7  AG3000_EM                              0.000000   November  2018
71   Siphon7  AG3000_EM                              0.000000   December  2018
72   Siphon7   IS203_EM                              6.893474    January  2018
73   Siphon7   IS203_EM                              0.000670   February  2018
74   Siphon7   IS203_EM                              0.000000      March  2018
75   Siphon7   IS203_EM                              0.000000      April  2018
76   Siphon7   IS203_EM                              0.000000        May  2018
77   Siphon7   IS203_EM                             56.220206       June  2018
78   Siphon7   IS203_EM                            129.029183       July  2018
79   Siphon7   IS203_EM                             89.107805     August  2018
80   Siphon7   IS203_EM                              0.000000  September  2018
81   Siphon7   IS203_EM                              0.000000    October  2018
82   Siphon7   IS203_EM                              0.000000   November  2018
83   Siphon7   IS203_EM                              0.000000   December  2018

[84 rows x 5 columns]

In [81]:
# Combine the two tables
match_fields = ['Siphon',
 'Meter',
 'Month',
 'Year']

df = pd.merge(df_sum, df_max, on=match_fields, how='outer')

In [83]:
cols = df.columns.tolist()

In [86]:
#Update the column sorting
cols =['Siphon',
       'Meter',
       'Year',
       'Month',
       'Maximum Rate of Diversion (GPM)',
       'Amount Directly Diverted (Acre Feet)']
df = df[cols]
df = df.fillna(0) 
df

,Siphon,Meter,Year,Month,Maximum Rate of Diversion (GPM),Amount Directly Diverted (Acre Feet)
0,Siphon11,IS203_EM,2018,January,0.0,0.000000
1,Siphon11,IS203_EM,2018,February,0.0,0.000000
2,Siphon11,IS203_EM,2018,March,0.0,0.000000
3,Siphon11,IS203_EM,2018,April,0.0,0.000000
4,Siphon11,IS203_EM,2018,May,2520.0,6.112861
5,Siphon11,IS203_EM,2018,June,4140.0,152.889690
6,Siphon11,IS203_EM,2018,July,5060.0,351.101473
7,Siphon11,IS203_EM,2018,August,0.0,0.000000
8,Siphon11,IS203_EM,2018,September,0.0,0.000000
9,Siphon11,IS203_EM,2018,October,0.0,0.000000
10,Siphon11,IS203_EM,2018,November,280.0,1.134509
11,Siphon11,IS203_EM,2018,December,200.0,0.010127
12,Siphon15,IS203_EM,2018,January,0.0,0.000000
13,Siphon15,IS203_EM,2018,February,0.0,0.000000
14,Siphon15,IS203_EM,2018,March,0.0,0.000000
15,Siphon15,IS203_EM,2018,April,0.0,0.000000
16,Siphon15,IS203_EM,2018,May,20.0,0.000307
17,Siphon15,IS203_EM,2018,June,4080.0,60.312799
18,Siphon15,IS203_EM,2018,July,4140.0,129.753136
19,Siphon15,IS203_EM,2018,August,4740.0,235.804974
20,Siphon15,IS203_EM,2018,September,60.0,0.003992
21,Siphon15,IS203_EM,2018,October,0.0,0.000000
22,Siphon15,IS203_EM,2018,November,5380.0,152.307869
23,Siphon15,IS203_EM,2018,December,80.0,0.059780
24,Siphon30,IS203_EM,2018,January,0.0,0.000000
25,Siphon30,IS203_EM,2018,February,0.0,0.000000
26,Siphon30,IS203_EM,2018,March,0.0,0.000000
27,Siphon30,IS203_EM,2018,April,40.0,0.001228
28,Siphon30,IS203_EM,2018,May,4740.0,62.307201
29,Siphon30,IS203_EM,2018,June,5260.0,250.720671
...,...,...,...,...,...,...
54,Siphon40,IS203_EM,2018,July,4820.0,396.397178
55,Siphon40,IS203_EM,2018,August,4400.0,406.666255
56,Siphon40,IS203_EM,2018,September,4200.0,62.245025
57,Siphon40,IS203_EM,2018,October,0.0,0.000000
58,Siphon40,IS203_EM,2018,November,0.0,0.000000
59,Siphon40,IS203_EM,2018,December,0.0,0.000000
60,Siphon7,AG3000_EM,2018,January,3420.0,15.844833
61,Siphon7,AG3000_EM,2018,February,0.0,0.000000
62,Siphon7,AG3000_EM,2018,March,0.0,0.000000
63,Siphon7,AG3000_EM,2018,April,0.0,0.000000
64,Siphon7,AG3000_EM,2018,May,0.0,0.000000
65,Siphon7,AG3000_EM,2018,June,3060.0,56.194800
66,Siphon7,AG3000_EM,2018,July,2520.0,128.459614
67,Siphon7,AG3000_EM,2018,August,2100.0,88.829124
68,Siphon7,AG3000_EM,2018,September,0.0,0.000000
69,Siphon7,AG3000_EM,2018,October,0.0,0.000000
70,Siphon7,AG3000_EM,2018,November,0.0,0.000000
71,Siphon7,AG3000_EM,2018,December,0.0,0.000000
72,Siphon7,IS203_EM,2018,January,3160.0,6.893474
73,Siphon7,IS203_EM,2018,February,40.0,0.000670
74,Siphon7,IS203_EM,2018,March,0.0,0.000000
75,Siphon7,IS203_EM,2018,April,0.0,0.000000
76,Siphon7,IS203_EM,2018,May,0.0,0.000000
77,Siphon7,IS203_EM,2018,June,3140.0,56.220206
78,Siphon7,IS203_EM,2018,July,2540.0,129.029183
79,Siphon7,IS203_EM,2018,August,2100.0,89.107805
80,Siphon7,IS203_EM,2018,September,0.0,0.000000
81,Siphon7,IS203_EM,2018,October,0.0,0.000000
82,Siphon7,IS203_EM,2018,November,0.0,0.000000
83,Siphon7,IS203_EM,2018,December,0.0,0.000000

In [88]:
# Export the report
df.to_csv(outdata_report, encoding='utf-8',index=False)