In [1]:
# Import data from sample files, modify, and export to new table

In [1]:
import pandas as pd
import os.path

In [2]:
year = '2019'
insample = os.path.join( os.getcwd(), 'samples\\sites.csv' )
indata = os.path.join( os.getcwd(), '..', year, 'input_data\\stations.xlsx' ) # created by hand from ArcGIS and other sources
outname = os.path.join( os.getcwd(), '..', year, 'sites.csv' )

In [3]:
df = pd.read_csv(insample)
df

,SiteCode,SiteName,Latitude,Longitude,LatLongDatumSRSName,Elevation_m,VerticalDatum,LocalX,LocalY,LocalProjectionSRSName,PosAccuracy_m,State,County,Comments,SiteType
0,Siphon7,StatenX experimental station at Siphon 7 on St...,38.1698,-121.527375,WGS84,NaN,NaN,NaN,NaN,NaN,NaN,California,San Joaquin,Site where multiple water meters are installed...,Diversion

In [4]:
# Modify the comment for siphon 7

new_comment = "Water Right ID: S018557; AG3000 Meter Serial Number: 032017001576; Telemetry ID: 001D0A8920278. " + df.at[0, 'Comments']
df.at[0, 'Comments'] = new_comment
df

,SiteCode,SiteName,Latitude,Longitude,LatLongDatumSRSName,Elevation_m,VerticalDatum,LocalX,LocalY,LocalProjectionSRSName,PosAccuracy_m,State,County,Comments,SiteType
0,Siphon7,StatenX experimental station at Siphon 7 on St...,38.1698,-121.527375,WGS84,NaN,NaN,NaN,NaN,NaN,NaN,California,San Joaquin,Water Right ID: S018557; AG3000 Meter Serial N...,Diversion

In [5]:
dfxl = pd.read_excel(open(indata,'rb'), sheet_name="sites")
dfxl

,SiteCode,SiteName,Latitude,Longitude,LatLongDatumSRSName,Elevation_m,VerticalDatum,LocalX,LocalY,LocalProjectionSRSName,PosAccuracy_m,State,County,Comments,SiteType
0,Siphon10,Siphon 10,38.156049,-121.534142,WGS84,NaN,NaN,NaN,NaN,NaN,NaN,California,San Joaquin,Water Right ID: S018584; Meter Serial Number: ...,Diversion
1,Siphon21,Siphon 21,38.122438,-121.530246,WGS84,NaN,NaN,NaN,NaN,NaN,NaN,California,San Joaquin,Water Right ID: S018553; Meter Serial Number: ...,Diversion
2,Siphon36,Siphon 36,38.173936,-121.497612,WGS84,NaN,NaN,NaN,NaN,NaN,NaN,California,San Joaquin,Water Right ID: S018528; Meter Serial Number: ...,Diversion
3,Siphon37,Siphon 37,38.182051,-121.489865,WGS84,NaN,NaN,NaN,NaN,NaN,NaN,California,San Joaquin,Water Right ID: S018543; Meter Serial Number: ...,Diversion
4,Siphon38,Siphon 38,38.191050,-121.482453,WGS84,NaN,NaN,NaN,NaN,NaN,NaN,California,San Joaquin,Water Right ID: S018566; Meter Serial Number: ...,Diversion
5,Siphon4,Siphon 4,38.184037,-121.523978,WGS84,NaN,NaN,NaN,NaN,NaN,NaN,California,San Joaquin,Water Right ID: S018563; Meter Serial Number: ...,Diversion
6,Siphon5,Siphon 5,38.178555,-121.525495,WGS84,NaN,NaN,NaN,NaN,NaN,NaN,California,San Joaquin,Water Right ID: S018560; Meter Serial Number: ...,Diversion
7,Siphon6,Siphon 6,38.173611,-121.523821,WGS84,NaN,NaN,NaN,NaN,NaN,NaN,California,San Joaquin,Water Right ID: S018575; Meter Serial Number: ...,Diversion
8,Siphon9,Siphon 9,38.157590,-121.534235,WGS84,NaN,NaN,NaN,NaN,NaN,NaN,California,San Joaquin,Water Right ID: S018569; Meter Serial Number: ...,Diversion

In [6]:
# Modify the sample table.  In this case, merge the sample data with the input data
df = df.append(dfxl, ignore_index=True)
df

,SiteCode,SiteName,Latitude,Longitude,LatLongDatumSRSName,Elevation_m,VerticalDatum,LocalX,LocalY,LocalProjectionSRSName,PosAccuracy_m,State,County,Comments,SiteType
0,Siphon7,StatenX experimental station at Siphon 7 on St...,38.169800,-121.527375,WGS84,NaN,NaN,NaN,NaN,NaN,NaN,California,San Joaquin,Water Right ID: S018557; AG3000 Meter Serial N...,Diversion
1,Siphon10,Siphon 10,38.156049,-121.534142,WGS84,NaN,NaN,NaN,NaN,NaN,NaN,California,San Joaquin,Water Right ID: S018584; Meter Serial Number: ...,Diversion
2,Siphon21,Siphon 21,38.122438,-121.530246,WGS84,NaN,NaN,NaN,NaN,NaN,NaN,California,San Joaquin,Water Right ID: S018553; Meter Serial Number: ...,Diversion
3,Siphon36,Siphon 36,38.173936,-121.497612,WGS84,NaN,NaN,NaN,NaN,NaN,NaN,California,San Joaquin,Water Right ID: S018528; Meter Serial Number: ...,Diversion
4,Siphon37,Siphon 37,38.182051,-121.489865,WGS84,NaN,NaN,NaN,NaN,NaN,NaN,California,San Joaquin,Water Right ID: S018543; Meter Serial Number: ...,Diversion
5,Siphon38,Siphon 38,38.191050,-121.482453,WGS84,NaN,NaN,NaN,NaN,NaN,NaN,California,San Joaquin,Water Right ID: S018566; Meter Serial Number: ...,Diversion
6,Siphon4,Siphon 4,38.184037,-121.523978,WGS84,NaN,NaN,NaN,NaN,NaN,NaN,California,San Joaquin,Water Right ID: S018563; Meter Serial Number: ...,Diversion
7,Siphon5,Siphon 5,38.178555,-121.525495,WGS84,NaN,NaN,NaN,NaN,NaN,NaN,California,San Joaquin,Water Right ID: S018560; Meter Serial Number: ...,Diversion
8,Siphon6,Siphon 6,38.173611,-121.523821,WGS84,NaN,NaN,NaN,NaN,NaN,NaN,California,San Joaquin,Water Right ID: S018575; Meter Serial Number: ...,Diversion
9,Siphon9,Siphon 9,38.157590,-121.534235,WGS84,NaN,NaN,NaN,NaN,NaN,NaN,California,San Joaquin,Water Right ID: S018569; Meter Serial Number: ...,Diversion

In [7]:
# Save as a new text file
df.to_csv(outname, encoding='utf-8', index=False)